spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - env:
        - name: "CHE_DOCKER_IP_EXTERNAL"
          valueFrom:
            configMapKeyRef:
              key: "hostname-http"
              name: "che"
        - name: "CHE_WORKSPACE_STORAGE"
          valueFrom:
            configMapKeyRef:
              key: "workspace-storage"
              name: "che"
        - name: "CHE_WORKSPACE_STORAGE_CREATE_FOLDERS"
          valueFrom:
            configMapKeyRef:
              key: "workspace-storage-create-folders"
              name: "che"
        - name: "CHE_LOCAL_CONF_DIR"
          valueFrom:
            configMapKeyRef:
              key: "local-conf-dir"
              name: "che"
        - name: "CHE_OPENSHIFT_PROJECT"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "CHE_OPENSHIFT_SERVICEACCOUNTNAME"
          valueFrom:
            configMapKeyRef:
              key: "openshift-serviceaccountname"
              name: "che"
        - name: "CHE_DOCKER_SERVER__EVALUATION__STRATEGY"
          valueFrom:
            configMapKeyRef:
              key: "che-server-evaluation-strategy"
              name: "che"
        - name: "CHE_LOG_LEVEL"
          valueFrom:
            configMapKeyRef:
              key: "log-level"
              name: "che"
        - name: "CHE_PORT"
          valueFrom:
            configMapKeyRef:
              key: "port"
              name: "che"
        - name: "CHE_DOCKER_CONNECTOR"
          valueFrom:
            configMapKeyRef:
              key: "docker-connector"
              name: "che"
        - name: "CHE_DEBUG_SERVER"
          valueFrom:
            configMapKeyRef:
              key: "remote-debugging-enabled"
              name: "che"
        image: "rhche/che-server:nightly"
        imagePullPolicy: "IfNotPresent"
        name: che
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 10
        ports:
        - containerPort: 8080
          name: "http"
        - containerPort: 8000
          name: "http-debug"
        volumeMounts:
        - mountPath: "/conf"
          name: "che-conf-volume"
          readOnly: false
        - mountPath: "/data"
          name: "che-data-volume"
      serviceAccountName: "che"
      volumes:
      - name: che-conf-volume
        persistentVolumeClaim:
          claimName: che-conf-volume
      - name: che-data-volume
        persistentVolumeClaim:
          claimName: che-data-volume
